### ISSUE TITLE
Images loading instanstly

### ISSUE THREAD

**Issue by juergengenser** [luis-almeida/unveil#8] opened 2013-05-28 13:13 UTC
I'm trying to implement unveil in a Wordpress-based site. It should target only a specific range of images - however, the images seem to load instantly, not when they are coming into the viewport. 

What could be the problem here?

Thanks,
Jürgen

**Comment by TheEskhaton** [comment] 2013-05-28 13:37
Did the console ouput any errors, what version of jQuery was included and in what browser did this happen in

**Comment by juergengenser** [comment] 2013-05-28 17:17
No console errors, jQuery version is 1.9.1 - I've tried Chrome, Safari and Firefox on Mac so far... I could share the link with you if this would be helpful?

**Comment by TheEskhaton** [comment] 2013-05-28 20:25
Of course, send a link and I'll look into it.

**Comment by andreasbecker** [comment] 2013-05-29 09:21
Same here. I'm trying to load PNGs. Can that be the cause?

**Comment by joeldbirch** [comment] 2013-06-01 09:45
Just checking: @juergengenser & @andreasbecker, are you altering the img tags that WordPress outputs, somehow, so that the image's URL is stored in data-src rather than src? If not, the images will load straight away, of course.

**Comment by andreasbecker** [comment] 2013-06-01 09:49
Problem was that width and height attributes were not set on the image tag. With them set it's working perfectly.

**Comment by joeldbirch** [comment] 2013-06-01 09:51
Ah, that is interesting. Often, people omit width and height attributes for responsive designs, but clearly they need to remain if this plugin is to work. Thanks for the info.

**Comment by joeldbirch** [comment] 2013-06-01 09:53
…although, relying on height attributes will result in imprecise calculations if the image is forced to scale with a responsive design, of course.

**Comment by foodini** [comment] 2013-07-12 16:42
I've seen the same everything-loads-at-page-load problem using both lazyload and unveil, even with the image width and height set.  I'm just fiddling with it on a throw-away page with 1x1 black images: http://foodini.org/fingerme.cgi

**Comment by luis-almeida** [comment] 2014-05-25 15:29
`width` and `height` attributes have anything to do with the way this plugin works. The demo page is a proof of that.
I'm closing this issue as it doesn't seem related to unveil itself but with the attempt of using in WP which I'm not familiar with.

**Closed as completed by luis-almeida** 2014-05-25 15:29 UTC
